proc ds2;
data;
   dcl date DS2_Date;
   dcl time DS2_Time;
   dcl timestamp DS2_Timestamp;
   dcl double SAS_Date SAS_Time SAS_Datetime;
   method init();
      DS2_Date= date '2013-04-28';
      DS2_Time= time '12:30:00';
      DS2_Timestamp= timestamp '2013-04-28 12:30:00';
      SAS_Date=to_double(DS2_Date); 
      SAS_Time=to_double(DS2_Time); 
      SAS_Datetime=to_double(DS2_Timestamp); 
      put DS2_Date= DS2_Time= DS2_Timestamp=;
      put SAS_Date=yymmdd10. SAS_Time=time. SAS_Datetime=datetime19.;
   end;
enddata;
run;
quit;
